import type { ArchitectureEdge, ArchitectureNode, ArchitectureNodeType } from "../types";
import type {
    CodeGenerationSummary,
    GeneratedArtifact,
    ProjectExecutionCheck,
    ProjectExecutionReport,
    ProjectGenerationResult,
} from "../types/codeGeneration";
import { buildArchitectureDNA } from "./architectureBrain";
import { analyzeImplementationIntelligence } from "./implementationIntelligence";

const MAX_ARTIFACTS = 120;
const MAX_SOURCE_LINES = 240;

const COMPUTE_TYPES: ArchitectureNodeType[] = ["backend", "api", "service", "worker"];

const slug = (value: string): string =>
    value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 48) || "component";

const unique = <T,>(items: T[]): T[] => [...new Set(items)];

function identifier(value: string): string {
    const base = slug(value).replace(/-([a-z])/g, (_, c: string) => c.toUpperCase()).replace(/[^a-zA-Z0-9_$]/g, "");
    return /^[a-zA-Z_$]/.test(base) ? base : `component${base}`;
}

function typeIdentifier(value: string): string {
    const base = identifier(value);
    return base.charAt(0).toUpperCase() + base.slice(1);
}

function nodeById(nodes: ArchitectureNode[]): Map<string, ArchitectureNode> {
    return new Map(nodes.map((node) => [node.id, node]));
}

function framework(nodes: ArchitectureNode[]): { framework: string; runtime: string; extension: string } {
    const text = nodes.map((node) => `${node.data.label} ${node.data.description}`).join(" ").toLowerCase();
    if (text.includes("next.js") || text.includes("nextjs")) return { framework: "Next.js", runtime: "Node.js", extension: "ts" };
    if (text.includes("react")) return { framework: "React + Vite", runtime: "Node.js", extension: "tsx" };
    if (text.includes("fastify")) return { framework: "Fastify", runtime: "Node.js", extension: "ts" };
    if (text.includes("express")) return { framework: "Express", runtime: "Node.js", extension: "ts" };
    if (text.includes("python")) return { framework: "Python service", runtime: "Python 3.12", extension: "py" };
    return { framework: "TypeScript service", runtime: "Node.js", extension: "ts" };
}

function projectName(nodes: ArchitectureNode[]): string {
    const primary = nodes.find((node) => node.data.type === "frontend") ?? nodes.find((node) => COMPUTE_TYPES.includes(node.data.type));
    return slug(primary?.data.label ?? "promptflow-app").replaceAll("-", "_").slice(0, 32);
}

function tsSourceFor(node: ArchitectureNode, edges: ArchitectureEdge[], byId: Map<string, ArchitectureNode>): string {
    const downstream = edges.filter((edge) => edge.source === node.id).map((edge) => byId.get(edge.target)?.data.label).filter(Boolean).slice(0, 6);
    const deps = downstream.length ? downstream.map((label) => `// → ${label}`).join("\n") : "// No downstream contract is represented yet.";
    return `/** ${node.data.label}\n * ${node.data.description}\n * Generated by PromptFlow Core 6. Treat this as a validated scaffold, not production-complete business logic.\n */\n\nexport interface ${typeIdentifier(node.data.label)}Config {\n  name: string;\n}\n\nexport async function ${identifier(node.data.label)}(): Promise<{ status: "ok"; component: string }> {\n  ${deps}\n  return { status: "ok", component: ${JSON.stringify(node.data.label)} };\n}\n`;
}

function pythonSourceFor(node: ArchitectureNode): string {
    const name = slug(node.data.label).replaceAll("-", "_");
    return `"""${node.data.description}\nGenerated by PromptFlow Core 6.\n"""\n\n\ndef ${name}() -> dict[str, str]:\n    return {"status": "ok", "component": ${JSON.stringify(node.data.label)}}\n`;
}

function frontendSourceFor(node: ArchitectureNode): string {
    return `import { useEffect, useState } from "react";\n\nexport function App() {\n  const [status, setStatus] = useState("connecting");\n\n  useEffect(() => {\n    setStatus("ready");\n  }, []);\n\n  return (\n    <main>\n      <h1>{${JSON.stringify(node.data.label)}}</h1>\n      <p>{${JSON.stringify(node.data.description)}}</p>\n      <p>Runtime: {status}</p>\n    </main>\n  );\n}\n`;
}

function testFor(node: ArchitectureNode, sourceContent: string): string {
    const fn = identifier(node.data.label);
    const hasGeneratedBoundary = new RegExp(
        `export\\s+(?:async\\s+)?function\\s+${fn}\\s*\\(`,
    ).test(sourceContent);

    if (!hasGeneratedBoundary) {
        return `await import("./${slug(node.data.label)}");
`;
    }

    return `import { ${fn} } from "./${slug(node.data.label)}";

const result = await ${fn}();
if (!result || result.status !== "ok") {
  throw new Error(${JSON.stringify(`${node.data.label} did not return a healthy execution boundary.`)});
}
`;
}

function testRunnerSource(): string {
    return `import { readdir } from "node:fs/promises";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

const componentDir = join(process.cwd(), "src", "components");
let entries: string[] = [];
try {
  entries = (await readdir(componentDir, { withFileTypes: true }))
    .filter((entry) => entry.isFile() && entry.name.endsWith(".test.ts"))
    .map((entry) => entry.name)
    .sort();
} catch (error) {
  const code = error && typeof error === "object" && "code" in error ? error.code : undefined;
  if (code !== "ENOENT") throw error;
}
  let failures = 0;

for (const file of entries) {
  try {
    await import(pathToFileURL(join(componentDir, file)).href);
    console.log(\`PASS \${file}\`);
  } catch (error) {
    failures += 1;
    console.error(\`FAIL \${file}\`, error);
  }
}

const exitCode = failures > 0 ? 1 : 0;
if (exitCode === 0) {
  console.log(\`PromptFlow tests passed: \${entries.length}/\${entries.length}\`);
}

// Generated application modules may initialize long-lived handles (for example
// an HTTP listener) during import. process.exitCode alone waits for those handles,
// which can keep npm test alive after every smoke test has already passed. All
// test imports above are awaited, so an explicit exit here is deterministic.
process.exit(exitCode);`;
}

function packageJson(name: string, runtime: string, stack: string[], hasReact: boolean): string {

    console.log(runtime);

    // function packageJson(name: string, stack: string[], hasReact: boolean): string {
    const dependencies: Record<string, string> = hasReact ? { react: "^19.2.8", "react-dom": "^19.2.8" } : {};
    if (stack.includes("Express")) dependencies.express = "^5.2.1";
    if (stack.includes("Fastify")) dependencies.fastify = "^5.0.0";

    const scripts = hasReact
        ? { dev: "vite", build: "tsc --noEmit && vite build", test: "tsx scripts/run-tests.ts", start: "vite preview" }
        : { dev: "tsx watch src/main.ts", build: "tsc", test: "tsx scripts/run-tests.ts", start: "node dist/main.js" };

    return JSON.stringify({
        name,
        private: true,
        version: "0.1.0",
        type: "module",
        scripts,
        dependencies,
        devDependencies: {
            "@types/node": "^24.13.3",
            typescript: "^6.0.2",
            ...(hasReact ? { vite: "^8.2.2" } : {}),
            tsx: "^4.19.4",
            ...(hasReact
                ? {
                    "@types/react": "^19.2.18",
                    "@types/react-dom": "^19.2.5",
                    "@vitejs/plugin-react": "^6.1.0",
                }
                : {}),
            ...(stack.includes("Express") ? { "@types/express": "^5.0.6" } : {}),
        },
    }, null, 2) + "\n";
}

function tsConfig(hasReact: boolean): string {
    return JSON.stringify(
        hasReact
            ? {
                compilerOptions: {
                    target: "ES2022",
                    module: "ESNext",
                    moduleResolution: "Bundler",
                    strict: true,
                    noEmit: true,
                    skipLibCheck: true,
                    esModuleInterop: true,
                    allowSyntheticDefaultImports: true,
                    jsx: "react-jsx",
                    types: ["vite/client"],
                },
                include: ["src"],
            }
            : {
                compilerOptions: {
                    target: "ES2022",
                    module: "NodeNext",
                    moduleResolution: "NodeNext",
                    strict: true,
                    rootDir: "src",
                    outDir: "dist",
                    declaration: false,
                    sourceMap: true,
                    // Recent TypeScript/@types-node combinations do not always
                    // auto-include the Node ambient types, which breaks on
                    // "node:*" built-in imports and Node globals like
                    // `process`. Declaring it explicitly makes the generated
                    // project build deterministically regardless of that
                    // auto-inclusion behavior.
                    types: ["node"],
                },
                include: ["src"],
                exclude: ["src/**/*.test.ts"],
            },
        null,
        2,
    ) + "\n";
}

function validateArtifacts(artifacts: GeneratedArtifact[]): ProjectExecutionCheck[] {
    const checks: ProjectExecutionCheck[] = [];
    const paths = artifacts.map((artifact) => artifact.path);
    const duplicate = paths.find((path, index) => paths.indexOf(path) !== index);
    checks.push({
        id: "unique-paths",
        status: duplicate ? "blocked" : "pass",
        title: "Artifact paths",
        message: duplicate ? `Duplicate generated path: ${duplicate}` : `${artifacts.length} unique artifacts generated.`,
    });
    const hasPackage = artifacts.some((artifact) => artifact.path === "package.json");
    checks.push({
        id: "package-manifest",
        status: hasPackage ? "pass" : "blocked",
        title: "Project manifest",
        message: hasPackage ? "package.json defines the generated runtime contract." : "No package manifest was generated.",
    });
    const hasSource = artifacts.some((artifact) => artifact.kind === "source");
    checks.push({
        id: "source",
        status: hasSource ? "pass" : "blocked",
        title: "Source surface",
        message: hasSource ? "At least one executable source artifact exists." : "No executable source artifact exists.",
    });
    const hasWebEntrypoint = artifacts.some((artifact) => artifact.path === "index.html" && artifacts.some((item) => item.path === "src/main.tsx"));
    const hasNodeEntrypoint = artifacts.some((artifact) => artifact.path === "src/main.ts");
    checks.push({
        id: "entrypoint",
        status: hasWebEntrypoint || hasNodeEntrypoint ? "pass" : "blocked",
        title: "Runtime entrypoint",
        message: hasWebEntrypoint ? "Web application entrypoint is present." : hasNodeEntrypoint ? "Node runtime entrypoint is present." : "No supported runtime entrypoint was generated.",
    });
    const oversized = artifacts.find((artifact) => artifact.content.split("\n").length > MAX_SOURCE_LINES);
    checks.push({
        id: "artifact-bounds",
        status: oversized ? "warning" : "pass",
        title: "Artifact bounds",
        message: oversized ? `${oversized.path} exceeds the scaffold line budget and should be reviewed.` : "Generated artifacts remain within the scaffold size budget.",
    });
    const testCount = artifacts.filter((artifact) => artifact.kind === "test").length;
    checks.push({
        id: "tests",
        status: testCount > 0 ? "pass" : "warning",
        title: "Test surface",
        message: testCount > 0 ? `${testCount} executable test scaffold(s) generated.` : "No test artifacts were generated.",
    });
    return checks;
}

export function validateGeneratedProject(result: ProjectGenerationResult): ProjectExecutionReport {
    const checks = validateArtifacts(result.artifacts);
    const missingCapabilities: string[] = [];
    if (!result.environment.length && result.artifacts.some((artifact) => artifact.path === ".env.example")) {
        missingCapabilities.push("Explicit runtime secrets/configuration should be reviewed.");
    }
    const blocked = checks.some((check) => check.status === "blocked");
    return {
        generatedAt: Date.now(),
        buildReady: !blocked,
        runReady: !blocked && result.entrypoints.length > 0,
        checks,
        commands: ["npm install --no-audit --no-fund", "npm test", "npm run build", "npm run start"],
        missingCapabilities,
    };
}

export function generateProjectFromArchitecture(
    nodes: ArchitectureNode[],
    edges: ArchitectureEdge[],
): ProjectGenerationResult {
    const meta = framework(nodes);
    const name = projectName(nodes);
    const byId = nodeById(nodes);
    const isReactViteProject = meta.framework === "React + Vite";
    const implementation = analyzeImplementationIntelligence(nodes, edges);
    const dna = buildArchitectureDNA(nodes, edges);
    const artifacts: GeneratedArtifact[] = [];

    artifacts.push({
        path: "package.json",
        kind: "config",
        language: "json",
        content: packageJson(name, meta.runtime, implementation.stack, isReactViteProject),
    });
    artifacts.push({
        path: "tsconfig.json",
        kind: "config",
        language: "json",
        content: tsConfig(isReactViteProject),
    });
    artifacts.push({
        path: ".env.example",
        kind: "config",
        language: "dotenv",
        content: implementation.environment.map((item) => `${item.name}=${item.secret ? "replace-me" : ""} # ${item.purpose}`).join("\n") + (implementation.environment.length ? "\n" : "# No explicit environment variables were inferred.\n"),
    });
    if (isReactViteProject) {
        artifacts.push({
            path: "index.html",
            kind: "config",
            language: "html",
            content: `<!doctype html>
<html lang="en">
  <head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>${name}</title></head>
  <body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body>
</html>
`,
        });
        artifacts.push({
            path: "src/main.tsx",
            kind: "source",
            language: "tsx",
            content: `import React from "react";
import { createRoot } from "react-dom/client";
import { App } from "./App";

createRoot(document.getElementById("root")!).render(
  <React.StrictMode><App /></React.StrictMode>,
);
`,
        });
        artifacts.push({
            path: "vite.config.ts",
            kind: "config",
            language: "typescript",
            content: `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
});
`,
        });
    } else {
        artifacts.push({
            path: "src/main.ts",
            kind: "source",
            language: "typescript",
            content: `import { createServer } from "node:http";

const server = createServer((_request, response) => {
  response.writeHead(200, { "content-type": "application/json" });
  response.end(JSON.stringify({ status: "ok", service: ${JSON.stringify(name)} }));
});

server.listen(Number(process.env.PORT ?? 3000), "0.0.0.0");
`,
        });
    }

    artifacts.push({
        path: "scripts/run-tests.ts",
        kind: "source",
        language: "typescript",
        content: testRunnerSource(),
    });

    for (const node of nodes) {
        if (artifacts.length >= MAX_ARTIFACTS - 4) break;
        const id = slug(node.data.label);
        const isPython = meta.runtime.startsWith("Python");
        let sourceContent: string;
        if (node.data.type === "frontend" && isReactViteProject) {
            sourceContent = frontendSourceFor(node);
            artifacts.push({ path: "src/App.tsx", kind: "source", language: "tsx", nodeId: node.id, content: sourceContent });
        } else if (isPython) {
            sourceContent = pythonSourceFor(node);
            artifacts.push({ path: `src/components/${id}.py`, kind: "source", language: "python", nodeId: node.id, content: sourceContent });
        } else {
            sourceContent = node.data.boilerplate.trim() || tsSourceFor(node, edges, byId);
            artifacts.push({ path: `src/components/${id}.ts`, kind: "source", language: "typescript", nodeId: node.id, content: sourceContent });
        }
        if (!isPython && (COMPUTE_TYPES.includes(node.data.type) || node.data.type === "service" || node.data.type === "worker")) {
            artifacts.push({
                path: `src/components/${id}.test.ts`,
                kind: "test",
                language: "typescript",
                nodeId: node.id,
                content: testFor(node, sourceContent),
            });
        }
    }

    const contractMarkdown = implementation.contracts.map((contract) =>
        `### ${contract.name}\n- Kind: ${contract.kind}\n- Boundary: ${contract.boundary}\n- Inputs: ${contract.inputs.join(", ")}\n- Outputs: ${contract.outputs.join(", ")}\n- Reliability: ${contract.reliabilityNotes.join(", ")}`,
    ).join("\n\n");
    artifacts.push({
        path: "docs/contracts.md",
        kind: "documentation",
        language: "markdown",
        content: `# Architecture contracts\n\n${contractMarkdown || "No explicit architecture contracts were represented."}\n`,
    });
    artifacts.push({
        path: "docs/ARCHITECTURE.md",
        kind: "documentation",
        language: "markdown",
        content: `# ${name}\n\nGenerated from PromptFlow architecture fingerprint **${dna.fingerprint}**.\n\n## DNA\n- Archetype: ${dna.archetype}\n- Traits: ${dna.traits.join(", ") || "none"}\n\n## Implementation\n${implementation.phases.map((phase) => `${phase.order}. ${phase.title} — ${phase.goal}`).join("\n") || "No implementation phases inferred."}\n\n> Generated scaffolds are starting points. Review security, persistence, error handling, and deployment configuration before production use.\n`,
    });

    const entrypoints = nodes
        .filter((node) => node.data.type === "frontend" || node.data.type === "backend" || node.data.type === "api")
        .map((node) => node.data.type === "frontend" && isReactViteProject
            ? "src/App.tsx"
            : node.data.type === "frontend"
                ? "src/main.ts"
                : `src/components/${slug(node.data.label)}.${meta.extension}`);
    const dependencies = unique([
        meta.framework,
        ...implementation.stack,
    ]).filter((item) => item !== "Node.js" && item !== "Python");

    const partial: ProjectGenerationResult = {
        generatedAt: Date.now(),
        modelVersion: "project-codegen-1.0",
        projectName: name,
        framework: meta.framework,
        runtime: meta.runtime,
        architectureFingerprint: dna.fingerprint,
        artifacts,
        entrypoints,
        dependencies,
        environment: implementation.environment.map((item) => item.name),
        contractsCovered: implementation.contracts.length,
        execution: {
            generatedAt: Date.now(),
            buildReady: false,
            runReady: false,
            checks: [],
            commands: [],
            missingCapabilities: [],
        },
    };
    return { ...partial, execution: validateGeneratedProject(partial) };
}

export function summarizeGeneratedProject(result: ProjectGenerationResult, nodes: ArchitectureNode[]): CodeGenerationSummary {
    const count = (kind: GeneratedArtifact["kind"]) => result.artifacts.filter((artifact) => artifact.kind === kind).length;
    return {
        sourceFiles: count("source"),
        configFiles: count("config"),
        testFiles: count("test"),
        documentationFiles: count("documentation") + count("schema"),
        totalFiles: result.artifacts.length,
        totalLines: result.artifacts.reduce((sum, artifact) => sum + artifact.content.split("\n").length, 0),
        nodeTypes: unique(nodes.map((node) => node.data.type)),
    };
}
